<?php

namespace Mary\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param string $name
     * @return object | null
     */
    public function findOneByName($name)
    {
        return $this->findOneBy(['username' => $name]);
    }
}
