# Web application configuration
mary_web:
    # Upload files configuration
    uploads:
        allowed_mime_types: ['image/jpeg', 'image/png', 'image/gif']
        groups:
            avatars:
                thumbnail_enabled: true
                thumbnail_sizes:
                    small:
                        width: 120
                        height: 90
                    medium:
                        width: 200
                        height: 150
                    large:
                        width: 680
                        height: 510