mary_admin:
    resource: "@MaryAdminBundle/Resources/config/routing.yml"
    prefix:   /

mary_web:
    resource: "@MaryWebBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
